/**
 * storeTemplates.js — Catálogo completo de produtos por nicho.
 * pexelsQuery em inglês para melhores resultados no Pexels.
 */

// ─────────────────────────────────────────────────────────────────────────────
// PIZZARIA  (64 produtos)
// ─────────────────────────────────────────────────────────────────────────────

const PIZZARIA = {
  type: 'food',
  categories: [
    { key: 'pizzas_salgadas', name: 'Pizzas Salgadas', order: 0 },
    { key: 'pizzas_doces',    name: 'Pizzas Doces',    order: 1 },
    { key: 'bebidas',         name: 'Bebidas',         order: 2 },
    { key: 'combos',          name: 'Combos',          order: 3 },
    { key: 'acompanhamentos', name: 'Acompanhamentos', order: 4 },
    { key: 'sobremesas',      name: 'Sobremesas',      order: 5 },
  ],
  products: [
    // Pizzas Salgadas (20)
    { category: 'pizzas_salgadas', name: 'Pizza Calabresa G',              price: 49.90, description: 'Calabresa fatiada, cebola e azeitona no molho artesanal.',            pexelsQuery: 'calabresa pizza slice close up' },
    { category: 'pizzas_salgadas', name: 'Pizza Portuguesa G',             price: 52.90, description: 'Presunto, ovo, cebola, azeitona e mussarela.',                         pexelsQuery: 'portuguese pizza traditional toppings' },
    { category: 'pizzas_salgadas', name: 'Pizza Frango Catupiry G',        price: 54.90, description: 'Frango desfiado com requeijão cremoso Catupiry.',                      pexelsQuery: 'chicken cream cheese pizza' },
    { category: 'pizzas_salgadas', name: 'Pizza Margherita G',             price: 46.90, description: 'Molho de tomate, mussarela fresca e manjericão.',                      pexelsQuery: 'margherita pizza fresh basil' },
    { category: 'pizzas_salgadas', name: 'Pizza Quatro Queijos G',         price: 56.90, description: 'Mussarela, provolone, parmesão e gorgonzola.',                         pexelsQuery: 'four cheese pizza melted' },
    { category: 'pizzas_salgadas', name: 'Pizza Pepperoni G',              price: 57.90, description: 'Pepperoni importado com mussarela cremosa.',                           pexelsQuery: 'pepperoni pizza close up appetizing' },
    { category: 'pizzas_salgadas', name: 'Pizza Napolitana G',             price: 49.90, description: 'Tomate, anchovas, alcaparras e azeitona preta.',                       pexelsQuery: 'neapolitan pizza rustic italian' },
    { category: 'pizzas_salgadas', name: 'Pizza Atum G',                   price: 51.90, description: 'Atum ao molho de tomate com cebola roxa e azeitona.',                  pexelsQuery: 'tuna pizza seafood' },
    { category: 'pizzas_salgadas', name: 'Pizza Milho com Bacon G',        price: 48.90, description: 'Milho verde, bacon crocante e catupiry.',                              pexelsQuery: 'corn bacon pizza golden' },
    { category: 'pizzas_salgadas', name: 'Pizza Vegetariana G',            price: 48.90, description: 'Abobrinha, berinjela, pimentão e tomate seco.',                        pexelsQuery: 'vegetarian pizza colorful vegetables' },
    { category: 'pizzas_salgadas', name: 'Pizza Mussarela G',              price: 42.90, description: 'Mussarela premium derretida com orégano fresco.',                      pexelsQuery: 'cheese pizza mozzarella melted' },
    { category: 'pizzas_salgadas', name: 'Pizza Carne Seca G',             price: 58.90, description: 'Carne seca desfiada, cebola caramelizada e catupiry.',                 pexelsQuery: 'pulled meat pizza rustic' },
    { category: 'pizzas_salgadas', name: 'Pizza Palmito G',                price: 50.90, description: 'Palmito pupunha, mussarela e azeitona verde.',                         pexelsQuery: 'hearts of palm pizza vegetarian' },
    { category: 'pizzas_salgadas', name: 'Pizza Frutos do Mar G',          price: 62.90, description: 'Camarão, lula e mariscos ao molho de tomate.',                         pexelsQuery: 'seafood pizza shrimp toppings' },
    { category: 'pizzas_salgadas', name: 'Pizza Brócolis com Alho G',      price: 46.90, description: 'Brócolis refogado no alho, mussarela e azeite.',                       pexelsQuery: 'broccoli garlic pizza italian' },
    { category: 'pizzas_salgadas', name: 'Pizza Lombinho G',               price: 52.90, description: 'Lombinho defumado, pimentão e mussarela.',                             pexelsQuery: 'smoked pork pizza slice' },
    { category: 'pizzas_salgadas', name: 'Pizza Bauru G',                  price: 50.90, description: 'Rosbife, queijo prato e tomate.',                                      pexelsQuery: 'roast beef cheese pizza' },
    { category: 'pizzas_salgadas', name: 'Pizza Strogonoff de Frango G',   price: 55.90, description: 'Frango ao strogonoff com batata palha crocante.',                      pexelsQuery: 'chicken stroganoff pizza creamy' },
    { category: 'pizzas_salgadas', name: 'Pizza Alho e Óleo G',            price: 44.90, description: 'Alho frito crocante, azeite extra virgem e orégano.',                  pexelsQuery: 'garlic olive oil pizza simple' },
    { category: 'pizzas_salgadas', name: 'Pizza Especial da Casa G',       price: 64.90, description: 'Receita exclusiva do chef com ingredientes premium.',                  pexelsQuery: 'gourmet special pizza restaurant' },
    // Pizzas Doces (8)
    { category: 'pizzas_doces',    name: 'Pizza Nutella com Morango G',    price: 54.90, description: 'Nutella generosa com morangos frescos fatiados.',                      pexelsQuery: 'nutella strawberry pizza dessert' },
    { category: 'pizzas_doces',    name: 'Pizza Brigadeiro G',             price: 52.90, description: 'Brigadeiro cremoso com granulado de chocolate.',                       pexelsQuery: 'chocolate brigadeiro pizza brazilian' },
    { category: 'pizzas_doces',    name: 'Pizza Romeu e Julieta G',        price: 50.90, description: 'Goiabada e queijo minas, combinação clássica brasileira.',              pexelsQuery: 'guava cheese dessert pizza sweet' },
    { category: 'pizzas_doces',    name: 'Pizza Banana com Canela G',      price: 48.90, description: 'Banana caramelizada com canela e leite condensado.',                   pexelsQuery: 'banana cinnamon sweet pizza dessert' },
    { category: 'pizzas_doces',    name: 'Pizza Prestígio G',              price: 52.90, description: 'Chocolate ao leite com coco ralado.',                                  pexelsQuery: 'chocolate coconut sweet pizza' },
    { category: 'pizzas_doces',    name: 'Pizza Doce de Leite G',          price: 50.90, description: 'Doce de leite cremoso com nozes picadas.',                             pexelsQuery: 'caramel walnut sweet pizza' },
    { category: 'pizzas_doces',    name: 'Pizza Bis G',                    price: 54.90, description: 'Chocolate meio amargo com pedaços de biscoito Bis.',                   pexelsQuery: 'chocolate cookie dessert pizza' },
    { category: 'pizzas_doces',    name: 'Pizza Morango com Chocolate G',  price: 53.90, description: 'Calda de chocolate com morangos frescos e chantilly.',                 pexelsQuery: 'strawberry chocolate dessert pizza' },
    // Bebidas (12)
    { category: 'bebidas', name: 'Coca Cola 2L',                price: 12.90, description: 'Garrafa 2 litros gelada.',                              pexelsQuery: 'coca cola bottle cold drink' },
    { category: 'bebidas', name: 'Coca Cola Lata 350ml',        price:  6.90, description: 'Lata 350ml gelada.',                                    pexelsQuery: 'coca cola can cold refreshing' },
    { category: 'bebidas', name: 'Guaraná Antarctica 2L',       price: 11.90, description: 'Garrafa 2L, sabor refrescante.',                        pexelsQuery: 'guarana soda bottle cold' },
    { category: 'bebidas', name: 'Pepsi Lata 350ml',            price:  6.90, description: 'Lata 350ml gelada.',                                    pexelsQuery: 'pepsi can soda cold drink' },
    { category: 'bebidas', name: 'Refrigerante Zero 2L',        price: 11.90, description: 'Versão zero açúcar, 2 litros.',                         pexelsQuery: 'diet soda zero sugar bottle' },
    { category: 'bebidas', name: 'Suco de Laranja Natural',     price:  9.90, description: 'Laranja fresca espremida na hora, 400ml.',              pexelsQuery: 'fresh squeezed orange juice glass' },
    { category: 'bebidas', name: 'Suco de Uva Integral 300ml',  price:  8.90, description: 'Suco de uva integral sem adição de açúcar.',            pexelsQuery: 'grape juice glass purple drink' },
    { category: 'bebidas', name: 'Água Mineral 500ml',          price:  4.90, description: 'Água mineral sem gás.',                                 pexelsQuery: 'mineral water bottle clear' },
    { category: 'bebidas', name: 'Água com Gás 500ml',          price:  5.90, description: 'Água mineral com gás.',                                 pexelsQuery: 'sparkling water glass bubbles' },
    { category: 'bebidas', name: 'Cerveja Heineken Long Neck',  price:  9.90, description: 'Long neck 330ml, gelada.',                              pexelsQuery: 'heineken beer bottle cold' },
    { category: 'bebidas', name: 'Cerveja Brahma Lata 350ml',   price:  6.90, description: 'Lata 350ml bem gelada.',                                pexelsQuery: 'beer can cold refreshing' },
    { category: 'bebidas', name: 'Limonada Suíça 400ml',        price: 11.90, description: 'Limonada cremosa com leite condensado.',                pexelsQuery: 'lemonade refreshing glass citrus' },
    // Combos (10)
    { category: 'combos', name: 'Combo 1 Pizza G + Refri 2L',   price: 58.90, description: '1 pizza grande à escolha + 1 refrigerante 2L.',        pexelsQuery: 'pizza soda combo meal delivery' },
    { category: 'combos', name: 'Combo 2 Pizzas M + Refri 2L',  price: 89.90, description: '2 pizzas médias + 1 refrigerante 2L.',                  pexelsQuery: 'two medium pizzas combo' },
    { category: 'combos', name: 'Combo Família',                 price:119.90, description: '2 pizzas grandes + 2 refrigerantes 2L.',               pexelsQuery: 'family pizza dinner table' },
    { category: 'combos', name: 'Combo Casal',                   price: 84.90, description: '2 pizzas médias + 2 cervejas long neck.',              pexelsQuery: 'couple pizza dinner romantic' },
    { category: 'combos', name: 'Combo Final de Semana',         price:149.90, description: '3 pizzas grandes + 3 refrigerantes 2L.',               pexelsQuery: 'pizza party weekend friends' },
    { category: 'combos', name: 'Combo Pizza Doce + Salgada',    price: 94.90, description: '1 pizza salgada G + 1 pizza doce M.',                  pexelsQuery: 'sweet and savory pizza duo' },
    { category: 'combos', name: 'Combo 3 Pizzas P',              price: 79.90, description: '3 pizzas pequenas à escolha.',                         pexelsQuery: 'three small pizzas variety' },
    { category: 'combos', name: 'Combo Executivo',               price: 64.90, description: '1 pizza média + 1 refrigerante lata + sobremesa.',     pexelsQuery: 'pizza lunch business combo' },
    { category: 'combos', name: 'Combo Aniversário',             price:189.90, description: '4 pizzas grandes + 4 refrigerantes 2L + sobremesa.',   pexelsQuery: 'birthday pizza party celebration' },
    { category: 'combos', name: 'Combo Pizza + Cerveja',         price: 68.90, description: '1 pizza grande + 4 cervejas lata.',                    pexelsQuery: 'pizza beer combo game night' },
    // Acompanhamentos (8)
    { category: 'acompanhamentos', name: 'Pão de Alho 6 un',          price: 14.90, description: 'Pão francês com manteiga de alho e ervas.',       pexelsQuery: 'garlic bread golden crispy' },
    { category: 'acompanhamentos', name: 'Pão de Alho com Catupiry',  price: 18.90, description: 'Pão de alho recheado com requeijão Catupiry.',     pexelsQuery: 'garlic bread cheese stuffed' },
    { category: 'acompanhamentos', name: 'Esfiha de Carne 6 un',      price: 22.90, description: 'Esfiha fechada com carne moída temperada.',        pexelsQuery: 'meat pastry esfiha arabic food' },
    { category: 'acompanhamentos', name: 'Coxinha de Frango 6 un',    price: 24.90, description: 'Coxinha crocante recheada com frango desfiado.',   pexelsQuery: 'coxinha chicken fried snack brazilian' },
    { category: 'acompanhamentos', name: 'Salada Caesar',             price: 22.90, description: 'Alface romana, croutons, parmesão e molho caesar.', pexelsQuery: 'caesar salad fresh restaurant' },
    { category: 'acompanhamentos', name: 'Batata Frita Crocante',     price: 18.90, description: 'Batata palito crocante com sal temperado, 200g.',  pexelsQuery: 'crispy french fries golden' },
    { category: 'acompanhamentos', name: 'Maionese de Alho 100g',     price:  8.90, description: 'Maionese artesanal de alho para acompanhar.',      pexelsQuery: 'garlic aioli sauce bowl' },
    { category: 'acompanhamentos', name: 'Borda Recheada (adicional)',price: 12.90, description: 'Adicional de borda recheada com catupiry.',        pexelsQuery: 'stuffed crust pizza cheese edge' },
    // Sobremesas (6)
    { category: 'sobremesas', name: 'Brownie com Sorvete',   price: 18.90, description: 'Brownie quente com sorvete de baunilha e calda.',    pexelsQuery: 'chocolate brownie warm ice cream' },
    { category: 'sobremesas', name: 'Petit Gateau',          price: 21.90, description: 'Bolinho de chocolate com centro quente e sorvete.',  pexelsQuery: 'petit gateau chocolate lava cake' },
    { category: 'sobremesas', name: 'Pudim de Leite',        price: 13.90, description: 'Pudim cremoso com calda de caramelo.',               pexelsQuery: 'caramel pudding dessert plate' },
    { category: 'sobremesas', name: 'Torta de Limão',        price: 16.90, description: 'Torta de limão siciliano com merengue.',             pexelsQuery: 'lemon meringue pie slice dessert' },
    { category: 'sobremesas', name: 'Cheesecake de Frutas',  price: 19.90, description: 'Cheesecake cremoso com calda de frutas vermelhas.',  pexelsQuery: 'cheesecake berry fruits dessert' },
    { category: 'sobremesas', name: 'Mousse de Chocolate',   price: 14.90, description: 'Mousse aerado de chocolate meio amargo.',            pexelsQuery: 'chocolate mousse dark dessert' },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// HAMBURGUERIA  (62 produtos)
// ─────────────────────────────────────────────────────────────────────────────

const HAMBURGUERIA = {
  type: 'food',
  categories: [
    { key: 'hamburgueres',    name: 'Hambúrgueres',    order: 0 },
    { key: 'bebidas',         name: 'Bebidas',         order: 1 },
    { key: 'combos',          name: 'Combos',          order: 2 },
    { key: 'acompanhamentos', name: 'Acompanhamentos', order: 3 },
    { key: 'sobremesas',      name: 'Sobremesas',      order: 4 },
  ],
  products: [
    // Hambúrgueres (22)
    { category: 'hamburgueres', name: 'Classic Burger',              price: 28.90, description: 'Blend 180g, queijo prato, alface, tomate e maionese artesanal.',     pexelsQuery: 'classic hamburger close up food' },
    { category: 'hamburgueres', name: 'Bacon Burger',                price: 34.90, description: 'Blend 180g, bacon crocante, cheddar e molho barbecue.',              pexelsQuery: 'bacon cheeseburger smash juicy' },
    { category: 'hamburgueres', name: 'Double Smash Burger',         price: 42.90, description: 'Dois blends 90g smashados, duplo cheddar e pickles.',               pexelsQuery: 'double smash burger dripping cheese' },
    { category: 'hamburgueres', name: 'Cheeseburger Artesanal',      price: 32.90, description: 'Blend 160g com três queijos e cebola caramelizada.',                pexelsQuery: 'artisan cheeseburger gourmet stack' },
    { category: 'hamburgueres', name: 'BBQ Burger',                  price: 36.90, description: 'Blend 180g, onion rings, barbecue e cheddar cremoso.',             pexelsQuery: 'bbq burger onion rings sauce' },
    { category: 'hamburgueres', name: 'Mushroom Burger',             price: 35.90, description: 'Cogumelos shitake refogados, queijo suíço e molho especial.',      pexelsQuery: 'mushroom burger swiss cheese' },
    { category: 'hamburgueres', name: 'Chicken Crispy Burger',       price: 29.90, description: 'Frango empanado crocante, coleslaw e mostarda mel.',               pexelsQuery: 'crispy chicken sandwich burger' },
    { category: 'hamburgueres', name: 'Veggie Burger',               price: 27.90, description: 'Blend de grão-de-bico, queijo e vegetais frescos.',               pexelsQuery: 'veggie burger plant based healthy' },
    { category: 'hamburgueres', name: 'Truffle Burger',              price: 46.90, description: 'Blend 200g, maionese de trufas e queijo brie.',                   pexelsQuery: 'truffle gourmet burger luxury' },
    { category: 'hamburgueres', name: 'Texas Burger',                price: 44.90, description: 'Blend duplo 360g, jalapeño, cheddar e chili.',                    pexelsQuery: 'texas burger big spicy' },
    { category: 'hamburgueres', name: 'X-Salada',                    price: 24.90, description: 'Hambúrguer 150g, queijo, alface, tomate e cebola.',               pexelsQuery: 'x salad burger simple classic' },
    { category: 'hamburgueres', name: 'X-Bacon',                     price: 28.90, description: 'Hambúrguer 150g, queijo, bacon e maionese.',                      pexelsQuery: 'x bacon burger fast food' },
    { category: 'hamburgueres', name: 'X-Egg',                       price: 26.90, description: 'Hambúrguer 150g, queijo, ovo e maionese.',                        pexelsQuery: 'egg burger breakfast style' },
    { category: 'hamburgueres', name: 'Smash Burger Simples',        price: 26.90, description: 'Blend 120g smashado, cheddar e pickles.',                         pexelsQuery: 'smash burger simple thin' },
    { category: 'hamburgueres', name: 'Frango Grelhado Burger',      price: 27.90, description: 'Peito de frango grelhado, alface, tomate e maionese light.',      pexelsQuery: 'grilled chicken burger healthy' },
    { category: 'hamburgueres', name: 'Fish Burger',                 price: 32.90, description: 'Filé de peixe empanado, alface e molho tártaro.',                 pexelsQuery: 'fish burger seafood sandwich' },
    { category: 'hamburgueres', name: 'Burger de Costela',           price: 48.90, description: 'Blend de costela bovina 200g com queijo defumado.',               pexelsQuery: 'beef rib burger smoked cheese' },
    { category: 'hamburgueres', name: 'Hawaiian Burger',             price: 33.90, description: 'Blend 180g, abacaxi grelhado, queijo e presunto.',               pexelsQuery: 'hawaiian burger pineapple' },
    { category: 'hamburgueres', name: 'Burger Kids',                 price: 19.90, description: 'Mini burguer 100g, queijinho e ketchup.',                         pexelsQuery: 'mini kids burger small cute' },
    { category: 'hamburgueres', name: 'Open Face Burger',            price: 38.90, description: 'Pão aberto, blend 200g, ovo frito e bacon.',                      pexelsQuery: 'open face burger egg fried' },
    { category: 'hamburgueres', name: 'Pulled Pork Burger',          price: 42.90, description: 'Blend 180g com pernil desfiado na pressão e molho bbq.',          pexelsQuery: 'pulled pork burger sandwich' },
    { category: 'hamburgueres', name: 'Burger de Alcatra',           price: 44.90, description: 'Blend de alcatra 200g, rúcula e parmesão.',                       pexelsQuery: 'premium beef burger arugula' },
    // Bebidas (10)
    { category: 'bebidas', name: 'Milkshake de Chocolate',    price: 18.90, description: 'Milkshake cremoso 400ml com calda de chocolate.',       pexelsQuery: 'chocolate milkshake thick straw' },
    { category: 'bebidas', name: 'Milkshake de Baunilha',     price: 18.90, description: 'Milkshake de baunilha 400ml com chantilly.',             pexelsQuery: 'vanilla milkshake creamy' },
    { category: 'bebidas', name: 'Milkshake de Morango',      price: 18.90, description: 'Milkshake 400ml com morangos frescos.',                  pexelsQuery: 'strawberry milkshake pink drink' },
    { category: 'bebidas', name: 'Milkshake Oreo',            price: 21.90, description: 'Milkshake com Oreo triturado e chantilly.',              pexelsQuery: 'oreo milkshake cookies cream' },
    { category: 'bebidas', name: 'Refrigerante Lata 350ml',   price:  6.90, description: 'Coca, Pepsi ou Guaraná 350ml.',                         pexelsQuery: 'soda can cold drink assorted' },
    { category: 'bebidas', name: 'Refrigerante 600ml',        price:  9.90, description: 'Garrafa 600ml à escolha.',                               pexelsQuery: 'soda bottle cold refreshing' },
    { category: 'bebidas', name: 'Limonada Suíça 400ml',      price: 12.90, description: 'Limonada cremosa com leite condensado.',                 pexelsQuery: 'lemonade refreshing glass citrus' },
    { category: 'bebidas', name: 'Água Mineral 500ml',        price:  4.90, description: 'Água mineral sem gás.',                                  pexelsQuery: 'mineral water bottle clear' },
    { category: 'bebidas', name: 'Cerveja Artesanal 355ml',   price: 14.90, description: 'Cerveja artesanal gelada, lata 355ml.',                  pexelsQuery: 'craft beer can cold artisan' },
    { category: 'bebidas', name: 'Suco Natural 400ml',        price: 10.90, description: 'Suco de laranja ou limão espremido na hora.',            pexelsQuery: 'fresh orange juice glass healthy' },
    // Combos (12)
    { category: 'combos', name: 'Combo Classic',          price: 42.90, description: 'Classic Burger + Batata Frita Crocante + Refri.',       pexelsQuery: 'burger fries combo meal' },
    { category: 'combos', name: 'Combo Double',           price: 56.90, description: 'Double Smash + Batata Frita + Milkshake.',              pexelsQuery: 'double burger combo milkshake' },
    { category: 'combos', name: 'Combo BBQ',              price: 50.90, description: 'BBQ Burger + Onion Rings + Refri.',                     pexelsQuery: 'bbq burger combo onion rings' },
    { category: 'combos', name: 'Combo Frango Crispy',    price: 44.90, description: 'Chicken Crispy + Batata Frita + Suco Natural.',         pexelsQuery: 'crispy chicken combo fries juice' },
    { category: 'combos', name: 'Combo Família',          price: 78.90, description: '2 Classic Burgers + 2 Batatas Fritas + 2 Refrigerantes.', pexelsQuery: 'family burger meal table' },
    { category: 'combos', name: 'Combo Kids',             price: 34.90, description: 'Kids Burger + Batata Palito + Suco de Caixinha.',        pexelsQuery: 'kids meal burger small' },
    { category: 'combos', name: 'Combo Casal',            price: 72.90, description: '2 Burgers à escolha + 2 acompanhamentos + 2 refris.',   pexelsQuery: 'couple burger meal sharing' },
    { category: 'combos', name: 'Combo Truffle',          price: 62.90, description: 'Truffle Burger + Fritas com Cheddar + Milkshake.',      pexelsQuery: 'gourmet truffle burger combo' },
    { category: 'combos', name: 'Combo Veggie',           price: 40.90, description: 'Veggie Burger + Salada + Suco Natural.',                pexelsQuery: 'veggie combo healthy meal' },
    { category: 'combos', name: 'Combo Texas',            price: 58.90, description: 'Texas Burger + Batata Recheada + Refri.',               pexelsQuery: 'texas burger combo big meal' },
    { category: 'combos', name: 'Combo Costela',          price: 64.90, description: 'Burger de Costela + Fritas + Cerveja Artesanal.',       pexelsQuery: 'rib burger premium combo beer' },
    { category: 'combos', name: 'Combo Aniversariante',   price: 54.90, description: '2 Burgers à escolha + 2 Milkshakes.',                  pexelsQuery: 'birthday burger celebration combo' },
    // Acompanhamentos (12)
    { category: 'acompanhamentos', name: 'Batata Frita Crocante 200g',  price: 16.90, description: 'Batata palito crocante com sal temperado.',        pexelsQuery: 'crispy french fries golden salted' },
    { category: 'acompanhamentos', name: 'Batata Frita Grande 300g',    price: 22.90, description: 'Porção grande de batata palito crocante.',          pexelsQuery: 'large french fries portion' },
    { category: 'acompanhamentos', name: 'Fritas com Cheddar e Bacon',  price: 24.90, description: 'Batata frita coberta com cheddar e bacon picado.',  pexelsQuery: 'loaded fries cheddar bacon sauce' },
    { category: 'acompanhamentos', name: 'Onion Rings 8 un',            price: 16.90, description: 'Anéis de cebola empanados crocantes.',              pexelsQuery: 'onion rings crispy golden fried' },
    { category: 'acompanhamentos', name: 'Batata Doce Frita 200g',      price: 18.90, description: 'Batata doce fatiada frita com mel e canela.',       pexelsQuery: 'sweet potato fries healthy golden' },
    { category: 'acompanhamentos', name: 'Nuggets de Frango 10 un',     price: 18.90, description: 'Nuggets crocantes de frango temperado.',            pexelsQuery: 'chicken nuggets crispy fried' },
    { category: 'acompanhamentos', name: 'Salada Caesar',               price: 16.90, description: 'Alface romana, croutons, parmesão e molho caesar.', pexelsQuery: 'caesar salad fresh restaurant' },
    { category: 'acompanhamentos', name: 'Salada Verde Mista',          price: 14.90, description: 'Mix de folhas, tomate cereja e pepino.',            pexelsQuery: 'mixed green salad fresh vegetables' },
    { category: 'acompanhamentos', name: 'Coleslaw Cremoso',            price: 12.90, description: 'Repolho, cenoura e maionese artesanal.',            pexelsQuery: 'coleslaw creamy side dish' },
    { category: 'acompanhamentos', name: 'Mac & Cheese 200g',           price: 19.90, description: 'Macarrão cremoso com cheddar e queijo prato.',      pexelsQuery: 'mac and cheese creamy comfort food' },
    { category: 'acompanhamentos', name: 'Batata Rústica ao Forno',     price: 18.90, description: 'Batata em cubos assada com ervas e alho.',          pexelsQuery: 'roasted potato wedges herbs' },
    { category: 'acompanhamentos', name: 'Anéis de Cebola com Cheddar', price: 19.90, description: 'Onion rings cobertos com cheddar cremoso.',         pexelsQuery: 'onion rings cheese sauce topping' },
    // Sobremesas (6)
    { category: 'sobremesas', name: 'Brownie com Sorvete',    price: 19.90, description: 'Brownie quente com sorvete e calda de chocolate.',   pexelsQuery: 'brownie ice cream warm dessert' },
    { category: 'sobremesas', name: 'Petit Gateau',           price: 22.90, description: 'Bolinho de chocolate com centro quente e sorvete.',  pexelsQuery: 'petit gateau chocolate lava cake' },
    { category: 'sobremesas', name: 'Churros com Doce de Leite', price: 16.90, description: '3 churros com doce de leite e açúcar e canela.', pexelsQuery: 'churros cinnamon sugar dessert' },
    { category: 'sobremesas', name: 'Pudim de Leite',         price: 13.90, description: 'Pudim caseiro com calda de caramelo.',               pexelsQuery: 'caramel pudding dessert plate' },
    { category: 'sobremesas', name: 'Donuts Recheados 2 un',  price: 17.90, description: '2 donuts recheados com Nutella ou doce de leite.',   pexelsQuery: 'donuts filled frosted dessert' },
    { category: 'sobremesas', name: 'Cookie Quente',          price: 14.90, description: 'Cookie recém-saído do forno com chocolate chips.',   pexelsQuery: 'warm chocolate chip cookie dessert' },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// AÇAÍ  (62 produtos)
// ─────────────────────────────────────────────────────────────────────────────

const ACAI = {
  type: 'food',
  categories: [
    { key: 'acai',         name: 'Açaí',         order: 0 },
    { key: 'complementos', name: 'Complementos', order: 1 },
    { key: 'bebidas',      name: 'Bebidas',      order: 2 },
    { key: 'combos',       name: 'Combos',       order: 3 },
    { key: 'vitaminas',    name: 'Vitaminas',    order: 4 },
  ],
  products: [
    // Açaí (15)
    { category: 'acai', name: 'Açaí Puro 300ml',              price: 14.90, description: 'Açaí puro cremoso 300ml sem adição de açúcar.',              pexelsQuery: 'acai bowl purple superfood' },
    { category: 'acai', name: 'Açaí Puro 500ml',              price: 22.90, description: 'Açaí puro cremoso 500ml.',                                    pexelsQuery: 'acai bowl large toppings' },
    { category: 'acai', name: 'Açaí Puro 700ml',              price: 29.90, description: 'Açaí puro cremoso 700ml.',                                    pexelsQuery: 'acai smoothie bowl big' },
    { category: 'acai', name: 'Açaí Puro 1L',                 price: 39.90, description: 'Açaí puro cremoso 1 litro — ideal para compartilhar.',        pexelsQuery: 'acai bowl one liter large' },
    { category: 'acai', name: 'Açaí Tigela P',                price: 18.90, description: 'Tigela pequena com granola e banana.',                        pexelsQuery: 'acai bowl granola banana small' },
    { category: 'acai', name: 'Açaí Tigela G',                price: 26.90, description: 'Tigela grande com granola, banana e morango.',                pexelsQuery: 'acai bowl strawberry topping' },
    { category: 'acai', name: 'Açaí Premium 500ml',           price: 28.90, description: 'Açaí com granola premium, mel, leite condensado e frutas.',   pexelsQuery: 'premium acai bowl colorful' },
    { category: 'acai', name: 'Açaí com Nutella 500ml',       price: 32.90, description: 'Açaí cremoso com Nutella e granola.',                         pexelsQuery: 'acai nutella chocolate bowl' },
    { category: 'acai', name: 'Açaí Fit 500ml',               price: 26.90, description: 'Açaí sem açúcar, granola sem glúten e frutas.',               pexelsQuery: 'healthy acai fitness bowl' },
    { category: 'acai', name: 'Açaí com Whey 500ml',          price: 34.90, description: 'Açaí 500ml + 1 dose de whey protein à escolha.',              pexelsQuery: 'protein acai bowl fitness gym' },
    { category: 'acai', name: 'Açaí Tropical 500ml',          price: 29.90, description: 'Açaí com manga, abacaxi e coco ralado.',                      pexelsQuery: 'tropical acai bowl mango pineapple' },
    { category: 'acai', name: 'Açaí de Morango 500ml',        price: 28.90, description: 'Açaí batido com morango e leite condensado.',                  pexelsQuery: 'strawberry acai smoothie bowl' },
    { category: 'acai', name: 'Açaí Kids 200ml',              price: 12.90, description: 'Porção infantil de açaí com granola colorida.',               pexelsQuery: 'small acai bowl kids colorful' },
    { category: 'acai', name: 'Açaí na Casquinha',            price: 10.90, description: 'Açaí cremoso servido na casquinha crocante.',                  pexelsQuery: 'acai ice cream cone waffle' },
    { category: 'acai', name: 'Açaí Especial da Casa 700ml',  price: 38.90, description: 'Receita exclusiva com coberturas especiais da casa.',          pexelsQuery: 'special acai bowl premium toppings' },
    // Complementos (20)
    { category: 'complementos', name: 'Granola Artesanal',      price:  3.00, description: 'Granola crocante com aveia, castanhas e mel.',        pexelsQuery: 'granola oats nuts honey healthy' },
    { category: 'complementos', name: 'Granola Sem Glúten',     price:  4.00, description: 'Granola sem glúten com quinoa e semente de chia.',    pexelsQuery: 'gluten free granola seeds' },
    { category: 'complementos', name: 'Morango Fresco',         price:  4.00, description: 'Morangos frescos fatiados.',                          pexelsQuery: 'fresh strawberries sliced red' },
    { category: 'complementos', name: 'Banana Fatiada',         price:  2.50, description: 'Banana prata fatiada.',                               pexelsQuery: 'banana sliced yellow fruit' },
    { category: 'complementos', name: 'Kiwi Fatiado',           price:  4.50, description: 'Kiwi fatiado fresco.',                                pexelsQuery: 'kiwi sliced green fruit fresh' },
    { category: 'complementos', name: 'Manga em Cubos',         price:  4.00, description: 'Manga palmer madura em cubos.',                       pexelsQuery: 'mango cubes tropical fruit' },
    { category: 'complementos', name: 'Uva sem Semente',        price:  4.00, description: 'Uvas frescas sem semente.',                           pexelsQuery: 'grapes fresh purple fruit' },
    { category: 'complementos', name: 'Mel Puro',               price:  3.00, description: 'Mel de abelha puro, 30g.',                            pexelsQuery: 'honey drizzle golden jar' },
    { category: 'complementos', name: 'Leite Condensado',       price:  3.50, description: 'Leite condensado cremoso, 30ml.',                     pexelsQuery: 'condensed milk sweet pouring' },
    { category: 'complementos', name: 'Nutella 30g',            price:  5.00, description: 'Dose de Nutella original.',                           pexelsQuery: 'nutella chocolate hazelnut spread' },
    { category: 'complementos', name: 'Pasta de Amendoim 30g', price:  4.00, description: 'Pasta de amendoim integral sem açúcar.',               pexelsQuery: 'peanut butter spoon healthy' },
    { category: 'complementos', name: 'Paçoca',                 price:  2.50, description: 'Paçoca de amendoim esfarelada.',                      pexelsQuery: 'peanut candy crumbled brazilian' },
    { category: 'complementos', name: 'Leite em Pó',            price:  2.00, description: 'Leite em pó integral.',                               pexelsQuery: 'milk powder food ingredient' },
    { category: 'complementos', name: 'Coco Ralado',            price:  2.00, description: 'Coco fresco ralado.',                                 pexelsQuery: 'shredded coconut white fresh' },
    { category: 'complementos', name: 'Chia',                   price:  2.50, description: 'Semente de chia, 15g.',                               pexelsQuery: 'chia seeds healthy superfood' },
    { category: 'complementos', name: 'Whey Protein 30g',       price:  7.00, description: 'Dose de whey protein (chocolate ou baunilha).',       pexelsQuery: 'whey protein scoop supplement' },
    { category: 'complementos', name: 'Castanha do Pará',       price:  4.50, description: 'Castanha do Pará picada, 20g.',                       pexelsQuery: 'brazil nuts healthy snack' },
    { category: 'complementos', name: 'Amendoim Crocante',      price:  2.50, description: 'Amendoim torrado e salgado picado.',                  pexelsQuery: 'roasted peanuts crunchy' },
    { category: 'complementos', name: 'Granulado de Chocolate', price:  2.00, description: 'Granulado colorido ou de chocolate.',                 pexelsQuery: 'chocolate sprinkles colorful' },
    { category: 'complementos', name: 'Calda de Chocolate',     price:  2.50, description: 'Calda de chocolate ao leite, 30ml.',                  pexelsQuery: 'chocolate sauce drizzle dark' },
    // Bebidas (12)
    { category: 'bebidas', name: 'Água de Coco Natural 300ml',    price:  9.90, description: 'Água de coco fresca gelada.',                        pexelsQuery: 'coconut water glass tropical' },
    { category: 'bebidas', name: 'Vitamina de Açaí 400ml',        price: 16.90, description: 'Vitamina de açaí com banana e leite de coco.',       pexelsQuery: 'acai smoothie purple drink' },
    { category: 'bebidas', name: 'Smoothie Tropical 400ml',       price: 14.90, description: 'Manga, abacaxi e maracujá 400ml.',                   pexelsQuery: 'tropical smoothie colorful glass' },
    { category: 'bebidas', name: 'Suco Verde Detox 350ml',        price: 12.90, description: 'Couve, limão, gengibre e pepino.',                   pexelsQuery: 'green detox juice healthy' },
    { category: 'bebidas', name: 'Suco de Laranja 400ml',         price:  9.90, description: 'Laranja espremida na hora.',                         pexelsQuery: 'fresh orange juice squeezed' },
    { category: 'bebidas', name: 'Suco de Morango 400ml',         price: 11.90, description: 'Morango com leite e açúcar.',                        pexelsQuery: 'strawberry juice smoothie glass' },
    { category: 'bebidas', name: 'Vitamina de Banana 400ml',      price: 10.90, description: 'Banana com leite e mel.',                            pexelsQuery: 'banana smoothie milk glass' },
    { category: 'bebidas', name: 'Bebida Isotônica 500ml',        price:  8.90, description: 'Isotônico gelado para repor eletrólitos.',            pexelsQuery: 'sports drink isotonic bottle' },
    { category: 'bebidas', name: 'Chá Gelado Hibisco 350ml',      price:  8.90, description: 'Chá de hibisco gelado sem açúcar.',                  pexelsQuery: 'hibiscus iced tea pink glass' },
    { category: 'bebidas', name: 'Água Mineral 500ml',            price:  4.90, description: 'Água mineral sem gás.',                              pexelsQuery: 'mineral water bottle clear' },
    { category: 'bebidas', name: 'Leite de Coco 300ml',           price:  9.90, description: 'Leite de coco gelado natural.',                      pexelsQuery: 'coconut milk glass tropical white' },
    { category: 'bebidas', name: 'Kombucha 350ml',                price: 12.90, description: 'Kombucha natural fermentada, sabores variados.',      pexelsQuery: 'kombucha fermented drink bottle' },
    // Combos (8)
    { category: 'combos', name: 'Combo Duplo Açaí',     price: 44.90, description: '2 Açaís 500ml com complementos à escolha.',     pexelsQuery: 'two acai bowls couple' },
    { category: 'combos', name: 'Combo Família',         price: 89.90, description: '4 Açaís 500ml + 4 complementos à escolha.',    pexelsQuery: 'family acai bowls table' },
    { category: 'combos', name: 'Combo Lanche Fit',      price: 36.90, description: 'Açaí Fit 500ml + Água de Coco + 3 complementos.', pexelsQuery: 'fitness healthy acai combo' },
    { category: 'combos', name: 'Combo Power',           price: 42.90, description: 'Açaí com Whey 500ml + Granola + Suco Verde.',  pexelsQuery: 'protein acai bowl power combo' },
    { category: 'combos', name: 'Combo Kids',            price: 26.90, description: 'Açaí Kids 200ml + 2 complementos + Vitamina.', pexelsQuery: 'kids acai healthy combo' },
    { category: 'combos', name: 'Combo Premium',         price: 62.90, description: '2 Açaís Premium 700ml + 2 Vitaminas.',         pexelsQuery: 'premium acai bowl duo' },
    { category: 'combos', name: 'Combo Tropical',        price: 48.90, description: '2 Açaís Tropical 500ml + Água de Coco.',       pexelsQuery: 'tropical acai bowl combo' },
    { category: 'combos', name: 'Combo Casal Fit',       price: 54.90, description: '2 Açaís Fit 700ml + 2 Kombucha.',              pexelsQuery: 'couple healthy acai kombucha' },
    // Vitaminas (7)
    { category: 'vitaminas', name: 'Vitamina de Abacate',     price: 14.90, description: 'Abacate, leite, mel e limão, 400ml.',         pexelsQuery: 'avocado smoothie green healthy' },
    { category: 'vitaminas', name: 'Vitamina de Mamão',       price: 12.90, description: 'Mamão com leite e mel, 400ml.',               pexelsQuery: 'papaya smoothie orange healthy' },
    { category: 'vitaminas', name: 'Vitamina de Goiaba',      price: 12.90, description: 'Goiaba com leite, 400ml.',                    pexelsQuery: 'guava juice smoothie pink' },
    { category: 'vitaminas', name: 'Vitamina Energética',     price: 16.90, description: 'Banana, aveia, mel e leite de coco.',         pexelsQuery: 'energy smoothie banana oats' },
    { category: 'vitaminas', name: 'Vitamina Antioxidante',   price: 18.90, description: 'Mirtilo, morango, açaí e leite de amêndoa.',  pexelsQuery: 'antioxidant smoothie berries purple' },
    { category: 'vitaminas', name: 'Vitamina Digestiva',      price: 14.90, description: 'Abacaxi, gengibre, hortelã e limão.',         pexelsQuery: 'digestive smoothie pineapple ginger' },
    { category: 'vitaminas', name: 'Vitamina Imunidade',      price: 17.90, description: 'Laranja, acerola, cúrcuma e mel.',            pexelsQuery: 'immunity booster orange smoothie' },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// SORVETERIA  (62 produtos)
// ─────────────────────────────────────────────────────────────────────────────

const SORVETERIA = {
  type: 'food',
  categories: [
    { key: 'sorvetes',   name: 'Sorvetes',      order: 0 },
    { key: 'acai',       name: 'Açaí',          order: 1 },
    { key: 'milkshakes', name: 'Milkshakes',    order: 2 },
    { key: 'combos',     name: 'Combos',        order: 3 },
    { key: 'especiais',  name: 'Especiais',     order: 4 },
  ],
  products: [
    // Sorvetes (22)
    { category: 'sorvetes', name: 'Casquinha Simples',              price:  7.90, description: '1 bola de sorvete em casquinha crocante.',                  pexelsQuery: 'ice cream cone single scoop' },
    { category: 'sorvetes', name: 'Casquinha Dupla',                price: 12.90, description: '2 bolas de sorvete em casquinha crocante.',                 pexelsQuery: 'double scoop ice cream cone' },
    { category: 'sorvetes', name: 'Casquinha Tripla',               price: 16.90, description: '3 bolas de sorvete em casquinha.',                          pexelsQuery: 'triple scoop ice cream cone tall' },
    { category: 'sorvetes', name: 'Sundae de Chocolate',            price: 16.90, description: 'Sorvete de creme com calda de chocolate e chantilly.',       pexelsQuery: 'chocolate sundae ice cream dessert' },
    { category: 'sorvetes', name: 'Sundae de Morango',              price: 16.90, description: 'Sorvete de creme com calda de morango.',                    pexelsQuery: 'strawberry sundae ice cream' },
    { category: 'sorvetes', name: 'Sundae de Caramelo',             price: 17.90, description: 'Sorvete com calda de caramelo e amêndoas.',                 pexelsQuery: 'caramel sundae ice cream nuts' },
    { category: 'sorvetes', name: 'Taça 3 Bolas',                   price: 21.90, description: 'Escolha 3 sabores com cobertura à escolha.',                pexelsQuery: 'three scoop ice cream bowl' },
    { category: 'sorvetes', name: 'Taça 5 Bolas',                   price: 32.90, description: '5 bolas com coberturas variadas e chantilly.',              pexelsQuery: 'five scoop ice cream large bowl' },
    { category: 'sorvetes', name: 'Sorvete no Pote 300ml',          price: 16.90, description: 'Pote 300ml no sabor à escolha.',                            pexelsQuery: 'ice cream small container cup' },
    { category: 'sorvetes', name: 'Sorvete no Pote 500ml',          price: 26.90, description: 'Pote 500ml no sabor à escolha.',                            pexelsQuery: 'ice cream pint container' },
    { category: 'sorvetes', name: 'Sorvete no Pote 1L',             price: 44.90, description: 'Pote 1L, ideal para compartilhar.',                         pexelsQuery: 'ice cream large container family' },
    { category: 'sorvetes', name: 'Sorvete no Pote 2L',             price: 79.90, description: 'Pote 2L para festas e eventos.',                            pexelsQuery: 'ice cream large tub party' },
    { category: 'sorvetes', name: 'Picolé Artesanal',               price:  8.90, description: 'Picolé artesanal sabores variados.',                        pexelsQuery: 'artisan popsicle ice cream bar' },
    { category: 'sorvetes', name: 'Picolé Recheado',                price: 12.90, description: 'Picolé recheado com chocolate ou Nutella.',                 pexelsQuery: 'stuffed popsicle chocolate filled' },
    { category: 'sorvetes', name: 'Banana Split',                   price: 28.90, description: 'Banana, 3 bolas, calda, chantilly e granulado.',            pexelsQuery: 'banana split dessert classic' },
    { category: 'sorvetes', name: 'Copa Dinamarquesa',              price: 26.90, description: '3 bolas com waffle crocante e calda quente.',               pexelsQuery: 'ice cream waffle cup dessert' },
    { category: 'sorvetes', name: 'Crepe com Sorvete',              price: 24.90, description: 'Crepe fino com sorvete e calda de chocolate.',              pexelsQuery: 'crepe ice cream chocolate dessert' },
    { category: 'sorvetes', name: 'Affogato',                       price: 19.90, description: 'Sorvete de baunilha com espresso quente.',                  pexelsQuery: 'affogato espresso ice cream italian' },
    { category: 'sorvetes', name: 'Taça Floresta Negra',            price: 29.90, description: 'Sorvete de chocolate, cerejas e chantilly.',                pexelsQuery: 'black forest ice cream dessert cherry' },
    { category: 'sorvetes', name: 'Float de Coca-Cola',             price: 18.90, description: 'Sorvete de baunilha com Coca-Cola gelada.',                 pexelsQuery: 'ice cream float coca cola' },
    { category: 'sorvetes', name: 'Waffle com Sorvete',             price: 26.90, description: 'Waffle belga quente com 2 bolas e calda.',                  pexelsQuery: 'waffle ice cream hot cold' },
    { category: 'sorvetes', name: 'Torta Gelada de Sorvete',        price: 49.90, description: 'Torta gelada com base de biscoito, porção para 4.',         pexelsQuery: 'ice cream cake frozen dessert' },
    // Açaí (10)
    { category: 'acai', name: 'Açaí 300ml',             price: 16.90, description: 'Açaí cremoso 300ml com granola e banana.',              pexelsQuery: 'acai bowl purple toppings small' },
    { category: 'acai', name: 'Açaí 500ml',             price: 24.90, description: 'Açaí cremoso 500ml com granola, banana e morango.',     pexelsQuery: 'acai bowl large granola' },
    { category: 'acai', name: 'Açaí 700ml',             price: 32.90, description: 'Açaí 700ml com complementos variados.',                 pexelsQuery: 'acai bowl big toppings' },
    { category: 'acai', name: 'Açaí Premium 500ml',     price: 30.90, description: 'Açaí premium com mel, Nutella e frutas.',               pexelsQuery: 'premium acai bowl colorful' },
    { category: 'acai', name: 'Açaí com Sorvete',       price: 28.90, description: 'Açaí 500ml com 1 bola de sorvete por cima.',            pexelsQuery: 'acai bowl ice cream scoop combo' },
    { category: 'acai', name: 'Açaí na Casquinha',      price: 12.90, description: 'Açaí cremoso na casquinha crocante.',                   pexelsQuery: 'acai ice cream cone waffle' },
    { category: 'acai', name: 'Açaí Tigela Pequena',    price: 20.90, description: 'Tigela pequena de açaí com granola e frutas.',          pexelsQuery: 'acai bowl small granola fruit' },
    { category: 'acai', name: 'Açaí Tigela Grande',     price: 30.90, description: 'Tigela grande com granola, frutas e mel.',              pexelsQuery: 'acai bowl strawberry large' },
    { category: 'acai', name: 'Açaí Fit 500ml',         price: 26.90, description: 'Açaí sem açúcar, chia e granola sem glúten.',           pexelsQuery: 'healthy acai fitness bowl' },
    { category: 'acai', name: 'Açaí Tropical 500ml',    price: 27.90, description: 'Açaí com manga, coco e abacaxi.',                       pexelsQuery: 'tropical acai bowl mango coconut' },
    // Milkshakes (12)
    { category: 'milkshakes', name: 'Milkshake de Chocolate',     price: 18.90, description: 'Milkshake cremoso 400ml com calda de chocolate.',    pexelsQuery: 'chocolate milkshake thick straw' },
    { category: 'milkshakes', name: 'Milkshake de Morango',       price: 18.90, description: 'Milkshake 400ml com morangos frescos.',               pexelsQuery: 'strawberry milkshake pink glass' },
    { category: 'milkshakes', name: 'Milkshake de Baunilha',      price: 17.90, description: 'Milkshake cremoso de baunilha 400ml.',                pexelsQuery: 'vanilla milkshake creamy' },
    { category: 'milkshakes', name: 'Milkshake Oreo',             price: 22.90, description: 'Milkshake com Oreo e chantilly.',                     pexelsQuery: 'oreo milkshake cookies cream' },
    { category: 'milkshakes', name: 'Milkshake de Maracujá',      price: 19.90, description: 'Milkshake de maracujá com leite condensado.',         pexelsQuery: 'passion fruit milkshake yellow' },
    { category: 'milkshakes', name: 'Milkshake Red Velvet',       price: 22.90, description: 'Milkshake de red velvet com cream cheese.',            pexelsQuery: 'red velvet milkshake dessert' },
    { category: 'milkshakes', name: 'Milkshake de Pistache',      price: 24.90, description: 'Milkshake de pistache com chantilly e granulado.',     pexelsQuery: 'pistachio milkshake green dessert' },
    { category: 'milkshakes', name: 'Milkshake de Amendoim',      price: 20.90, description: 'Milkshake com pasta de amendoim e banana.',            pexelsQuery: 'peanut butter milkshake banana' },
    { category: 'milkshakes', name: 'Milkshake de Limão',         price: 18.90, description: 'Milkshake cítrico de limão siciliano.',                pexelsQuery: 'lemon milkshake citrus yellow' },
    { category: 'milkshakes', name: 'Milkshake Nutella',          price: 23.90, description: 'Milkshake de Nutella com avelã.',                      pexelsQuery: 'nutella milkshake hazelnut chocolate' },
    { category: 'milkshakes', name: 'Milkshake de Menta',         price: 19.90, description: 'Milkshake de menta com pedaços de chocolate.',         pexelsQuery: 'mint chocolate chip milkshake green' },
    { category: 'milkshakes', name: 'Milkshake Frutas Vermelhas', price: 20.90, description: 'Milkshake de mirtilo, framboesa e morango.',           pexelsQuery: 'mixed berry milkshake red purple' },
    // Combos (8)
    { category: 'combos', name: 'Combo Casal',          price: 38.90, description: '2 Taças 3 Bolas + 2 Milkshakes.',                     pexelsQuery: 'couple ice cream desserts table' },
    { category: 'combos', name: 'Combo Família',        price: 64.90, description: '4 Casquinhas Duplas + 2 Milkshakes + 1 Açaí.',        pexelsQuery: 'family ice cream dessert' },
    { category: 'combos', name: 'Combo Sorvete + Açaí', price: 40.90, description: 'Taça 3 Bolas + Açaí 500ml.',                         pexelsQuery: 'ice cream acai bowl combo' },
    { category: 'combos', name: 'Combo Kids',           price: 28.90, description: 'Casquinha Dupla + Milkshake + Picolé Artesanal.',     pexelsQuery: 'kids ice cream combo colorful' },
    { category: 'combos', name: 'Combo Sundae Duplo',   price: 32.90, description: '2 Sundaes à escolha + 2 coberturas.',                 pexelsQuery: 'double sundae combo dessert' },
    { category: 'combos', name: 'Combo Aniversário',    price: 89.90, description: 'Torta Gelada + 4 Milkshakes + 4 Casquinhas.',         pexelsQuery: 'ice cream birthday party combo' },
    { category: 'combos', name: 'Combo Verão',          price: 46.90, description: '2 Float Coca-Cola + 2 Picolés Artesanais.',           pexelsQuery: 'summer ice cream float combo' },
    { category: 'combos', name: 'Combo Especial',       price: 52.90, description: 'Banana Split + 2 Milkshakes.',                        pexelsQuery: 'special ice cream combo banana split' },
    // Especiais (10)
    { category: 'especiais', name: 'Brownie com Sorvete',       price: 22.90, description: 'Brownie quente com sorvete e calda de chocolate.',   pexelsQuery: 'brownie ice cream warm dessert' },
    { category: 'especiais', name: 'Waffle Belga Recheado',     price: 28.90, description: 'Waffle com sorvete, Nutella e frutas.',              pexelsQuery: 'belgian waffle ice cream nutella' },
    { category: 'especiais', name: 'Crepe Gelado Especial',     price: 24.90, description: 'Crepe fino, sorvete, frutas e calda de chocolate.',  pexelsQuery: 'crepe ice cream chocolate special' },
    { category: 'especiais', name: 'Fondue de Chocolate',       price: 34.90, description: 'Fondue de chocolate com frutas e marshmallow.',      pexelsQuery: 'chocolate fondue fruit dessert' },
    { category: 'especiais', name: 'Torta Gelada Individual',   price: 19.90, description: 'Torta gelada porção individual com calda.',          pexelsQuery: 'ice cream cake individual portion' },
    { category: 'especiais', name: 'Cookie Sanduba',            price: 18.90, description: '2 cookies artesanais recheados com sorvete.',        pexelsQuery: 'ice cream cookie sandwich dessert' },
    { category: 'especiais', name: 'Churros com Sorvete',       price: 22.90, description: 'Churros com cinnamon sugar e sorvete de baunilha.',  pexelsQuery: 'churros ice cream cinnamon dessert' },
    { category: 'especiais', name: 'Profiteroles',              price: 26.90, description: '6 profiteroles com sorvete e calda de chocolate.',   pexelsQuery: 'profiteroles cream puff ice cream' },
    { category: 'especiais', name: 'Pavê Gelado Individual',    price: 18.90, description: 'Pavê cremoso gelado com biscoito e chocolate.',      pexelsQuery: 'cold trifle dessert cream layers' },
    { category: 'especiais', name: 'Sorvete Frito',             price: 24.90, description: 'Sorvete empanado e frito, servido com calda.',       pexelsQuery: 'fried ice cream crispy dessert' },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// FARMÁCIA  (158 produtos)
// ─────────────────────────────────────────────────────────────────────────────

const FARMACIA = {
  type: 'pharmacy',
  categories: [
    { key: 'dor_febre',  name: 'Dor e Febre',  order: 0 },
    { key: 'vitaminas',  name: 'Vitaminas',    order: 1 },
    { key: 'higiene',    name: 'Higiene',      order: 2 },
    { key: 'bebe',       name: 'Bebê',         order: 3 },
    { key: 'beleza',     name: 'Beleza',       order: 4 },
    { key: 'genericos',  name: 'Genéricos',    order: 5 },
  ],
  products: [
    // Dor e Febre (22)
    { category: 'dor_febre', name: 'Dipirona 500mg 20cp',            price:  9.90, description: 'Analgésico e antitérmico de rápida ação, 20 comprimidos.',         pexelsQuery: 'medicine pills pharmacy painkiller',       requiresPrescription: false },
    { category: 'dor_febre', name: 'Dipirona Gotas 20ml',            price: 12.90, description: 'Dipirona solução oral 500mg/ml, 20ml.',                             pexelsQuery: 'medicine drops bottle pharmacy',           requiresPrescription: false },
    { category: 'dor_febre', name: 'Paracetamol 750mg 20cp',         price:  8.90, description: 'Analgésico e antitérmico, 20 comprimidos.',                         pexelsQuery: 'paracetamol tablets white pills',          requiresPrescription: false },
    { category: 'dor_febre', name: 'Paracetamol Xarope 120ml',       price: 14.90, description: 'Xarope infantil 200mg/5ml, sabor morango.',                         pexelsQuery: 'medicine syrup bottle red pharmacy',       requiresPrescription: false },
    { category: 'dor_febre', name: 'Ibuprofeno 400mg 20cp',          price: 11.90, description: 'Anti-inflamatório e analgésico, 20 comprimidos.',                   pexelsQuery: 'ibuprofen tablets medicine box',           requiresPrescription: false },
    { category: 'dor_febre', name: 'Ibuprofeno 600mg 20cp',          price: 13.90, description: 'Anti-inflamatório e analgésico 600mg, 20 comprimidos.',             pexelsQuery: 'anti inflammatory medicine tablets',       requiresPrescription: false },
    { category: 'dor_febre', name: 'Aspirina 500mg 20cp',            price:  9.90, description: 'Ácido acetilsalicílico, 20 comprimidos efervescentes.',             pexelsQuery: 'aspirin effervescent tablets water',       requiresPrescription: false },
    { category: 'dor_febre', name: 'Aspirina Prevent 100mg 30cp',    price: 18.90, description: 'AAS 100mg para proteção cardiovascular.',                           pexelsQuery: 'aspirin cardiovascular small tablets',     requiresPrescription: false },
    { category: 'dor_febre', name: 'Buscopan Composto 20cp',         price: 16.90, description: 'Antiespasmódico com analgésico, 20 comprimidos.',                   pexelsQuery: 'stomach medicine capsules healthcare',     requiresPrescription: false },
    { category: 'dor_febre', name: 'Tylenol Sinus 24cp',             price: 18.90, description: 'Alívio de sinusite e congestão nasal.',                             pexelsQuery: 'headache sinus medicine blister pack',     requiresPrescription: false },
    { category: 'dor_febre', name: 'Nimesulida 100mg 12cp',          price: 12.90, description: 'Anti-inflamatório — requer receita médica.',                        pexelsQuery: 'anti inflammatory prescription medicine',  requiresPrescription: true  },
    { category: 'dor_febre', name: 'Diclofenaco 50mg 20cp',          price: 11.90, description: 'Anti-inflamatório e analgésico.',                                   pexelsQuery: 'diclofenac anti inflammatory pills',       requiresPrescription: true  },
    { category: 'dor_febre', name: 'Voltaren Gel 40g',               price: 32.90, description: 'Gel anti-inflamatório diclofenaco de sódio para uso tópico.',       pexelsQuery: 'pain relief gel tube pharmacy', requiresPrescription: false },
    { category: 'dor_febre', name: 'Gelol Gel 60g',                  price: 22.90, description: 'Gel refrescante para alívio de dores musculares e articulares.',    pexelsQuery: 'cooling gel muscle pain relief',           requiresPrescription: false },
    { category: 'dor_febre', name: 'Sal de Fruta Eno 100g',          price: 12.90, description: 'Antiácido efervescente para azia e má digestão.',                   pexelsQuery: 'antacid effervescent stomach relief',      requiresPrescription: false },
    { category: 'dor_febre', name: 'Omeprazol 20mg 28cp',            price: 24.90, description: 'Protetor gástrico para gastrite e refluxo, 28 cápsulas.',           pexelsQuery: 'omeprazole capsules gastric medicine',     requiresPrescription: true  },
    { category: 'dor_febre', name: 'Estomazil Suspensão 240ml',      price: 21.90, description: 'Antiácido suspensão oral para alívio de queimação.',                pexelsQuery: 'antacid liquid suspension bottle',         requiresPrescription: false },
    { category: 'dor_febre', name: 'Cataflam 50mg 20cp',             price: 28.90, description: 'Diclofenaco potássico para dor aguda.',                             pexelsQuery: 'pain reliever tablets prescription',       requiresPrescription: true  },
    { category: 'dor_febre', name: 'Tylenol 750mg 20cp',             price: 18.90, description: 'Paracetamol 750mg alívio de dores e febre.',                        pexelsQuery: 'tylenol paracetamol fever relief',         requiresPrescription: false },
    { category: 'dor_febre', name: 'Coristina D 16cp',               price: 22.90, description: 'Antialérgico e descongestionante para resfriados.',                 pexelsQuery: 'cold flu medicine tablets antihistamine',  requiresPrescription: false },
    { category: 'dor_febre', name: 'Neosaldina 16cp',                price: 19.90, description: 'Analgésico para dor de cabeça com cafeína.',                        pexelsQuery: 'headache medicine caffeine tablets',       requiresPrescription: false },
    { category: 'dor_febre', name: 'Naldecon Xarope 120ml',          price: 24.90, description: 'Descongestionante nasal xarope para adultos.',                      pexelsQuery: 'cough syrup decongestant bottle',          requiresPrescription: false },
    // Vitaminas (22)
    { category: 'vitaminas', name: 'Vitamina C 1g Efervescente 10cp',  price: 18.90, description: '10 comprimidos efervescentes sabor laranja.',                    pexelsQuery: 'vitamin c effervescent tablet orange',     requiresPrescription: false },
    { category: 'vitaminas', name: 'Vitamina C 500mg 60cp',            price: 22.90, description: 'Vitamina C em comprimidos, 60 unidades.',                         pexelsQuery: 'vitamin c supplement tablets orange',      requiresPrescription: false },
    { category: 'vitaminas', name: 'Vitamina D3 2000UI 60cp',          price: 26.90, description: '60 cápsulas — imunidade e saúde óssea.',                          pexelsQuery: 'vitamin d supplement capsules sunshine',   requiresPrescription: false },
    { category: 'vitaminas', name: 'Vitamina D3 5000UI 30cp',          price: 34.90, description: 'Alta concentração, 30 cápsulas.',                                 pexelsQuery: 'vitamin d3 high dose supplement',          requiresPrescription: false },
    { category: 'vitaminas', name: 'Vitamina B12 1000mcg 60cp',        price: 28.90, description: 'B12 para energia, memória e sistema nervoso.',                    pexelsQuery: 'vitamin b12 supplement energy',            requiresPrescription: false },
    { category: 'vitaminas', name: 'Vitamina E 400UI 30cp',            price: 32.90, description: 'Antioxidante para pele e sistema imune.',                         pexelsQuery: 'vitamin e antioxidant capsules',           requiresPrescription: false },
    { category: 'vitaminas', name: 'Vitamina A 10000UI 30cp',          price: 24.90, description: 'Vitamina A para visão e imunidade.',                              pexelsQuery: 'vitamin a supplement bottle',              requiresPrescription: false },
    { category: 'vitaminas', name: 'Ômega 3 1g 60cp',                  price: 34.90, description: 'EPA + DHA para saúde cardiovascular.',                            pexelsQuery: 'omega 3 fish oil capsules health',         requiresPrescription: false },
    { category: 'vitaminas', name: 'Ômega 3 2g 90cp',                  price: 54.90, description: 'Dose dupla EPA + DHA, embalagem econômica.',                      pexelsQuery: 'omega 3 large bottle supplement',          requiresPrescription: false },
    { category: 'vitaminas', name: 'Complexo B 60cp',                  price: 21.90, description: 'Todas as vitaminas do complexo B, 60 comprimidos.',               pexelsQuery: 'vitamin b complex supplement yellow',      requiresPrescription: false },
    { category: 'vitaminas', name: 'Magnésio Dimalato 60cp',           price: 38.90, description: 'Magnésio de alta absorção para energia e sono.',                  pexelsQuery: 'magnesium supplement bottle healthcare',   requiresPrescription: false },
    { category: 'vitaminas', name: 'Magnésio + B6 60cp',               price: 28.90, description: 'Relaxamento muscular e redução do estresse.',                     pexelsQuery: 'magnesium b6 supplement stress',           requiresPrescription: false },
    { category: 'vitaminas', name: 'Zinco Quelato 30mg 60cp',          price: 24.90, description: '60 comprimidos — imunidade e pele saudável.',                     pexelsQuery: 'zinc supplement tablets immunity',         requiresPrescription: false },
    { category: 'vitaminas', name: 'Ferro + Ácido Fólico 60cp',        price: 26.90, description: 'Suplemento de ferro com ácido fólico.',                           pexelsQuery: 'iron folic acid supplement pregnancy',     requiresPrescription: false },
    { category: 'vitaminas', name: 'Cálcio + Vitamina D 60cp',         price: 32.90, description: 'Cálcio com vitamina D para ossos fortes.',                        pexelsQuery: 'calcium vitamin d bone health supplement',  requiresPrescription: false },
    { category: 'vitaminas', name: 'Multivitamínico A-Z 60cp',         price: 36.90, description: 'Fórmula completa com 23 vitaminas e minerais.',                   pexelsQuery: 'multivitamin colorful pills supplement',   requiresPrescription: false },
    { category: 'vitaminas', name: 'Multivitamínico Feminino 60cp',    price: 42.90, description: 'Fórmula especial para a saúde da mulher.',                        pexelsQuery: 'womens multivitamin supplement health',    requiresPrescription: false },
    { category: 'vitaminas', name: 'Multivitamínico Infantil 60 gomas',price: 44.90, description: 'Vitaminas em gomas sabor frutas para crianças.',                  pexelsQuery: 'childrens gummy vitamins colorful',        requiresPrescription: false },
    { category: 'vitaminas', name: 'Colágeno Hidrolisado + Vit C 60cp',price: 42.90, description: 'Colágeno para pele, cabelo e articulações.',                      pexelsQuery: 'collagen supplement beauty skin health',   requiresPrescription: false },
    { category: 'vitaminas', name: 'Biotina 10000mcg 60cp',            price: 38.90, description: 'Vitamina H para cabelo, unhas e pele.',                           pexelsQuery: 'biotin supplement hair growth vitamins',   requiresPrescription: false },
    { category: 'vitaminas', name: 'Coenzima Q10 100mg 30cp',          price: 48.90, description: 'Antioxidante para energia celular e coração.',                    pexelsQuery: 'coq10 coenzyme supplement energy',         requiresPrescription: false },
    { category: 'vitaminas', name: 'Probiótico 10 bilhões 30cp',       price: 52.90, description: '10 cepas probióticas para saúde intestinal.',                     pexelsQuery: 'probiotic supplement gut health capsules', requiresPrescription: false },
    // Higiene (32)
    { category: 'higiene', name: 'Shampoo Anticaspa 400ml',            price: 18.90, description: 'Controla caspa e oleosidade com ZPT.',                            pexelsQuery: 'shampoo bottle hair care dandruff' },
    { category: 'higiene', name: 'Shampoo Hidratante 400ml',           price: 16.90, description: 'Hidratação intensa para cabelos ressecados.',                     pexelsQuery: 'moisturizing shampoo bottle haircare' },
    { category: 'higiene', name: 'Condicionador 400ml',                price: 16.90, description: 'Condicionador com proteína de seda.',                             pexelsQuery: 'conditioner bottle hair treatment' },
    { category: 'higiene', name: 'Máscara Capilar 300g',               price: 28.90, description: 'Máscara de hidratação profunda para cabelos.',                   pexelsQuery: 'hair mask treatment deep conditioning' },
    { category: 'higiene', name: 'Protetor Solar FPS 50 120ml',        price: 44.90, description: 'Proteção UVA+UVB, pele oleosa, sem oleosidade.',                 pexelsQuery: 'sunscreen sunblock protection beach' },
    { category: 'higiene', name: 'Protetor Solar FPS 70 120ml',        price: 52.90, description: 'Proteção máxima UVA+UVB para uso diário.',                       pexelsQuery: 'high spf sunscreen lotion tube' },
    { category: 'higiene', name: 'Creme Hidratante Corporal 200g',     price: 26.90, description: 'Hidratação profunda 24h para o corpo.',                           pexelsQuery: 'body lotion moisturizer skincare' },
    { category: 'higiene', name: 'Creme de Mãos 75g',                  price: 14.90, description: 'Creme hidratante de rápida absorção para mãos.',                 pexelsQuery: 'hand cream moisturizer tube' },
    { category: 'higiene', name: 'Antisséptico Bucal 500ml',           price: 14.90, description: 'Listerine menta — proteção completa 12h.',                       pexelsQuery: 'mouthwash bottle dental hygiene' },
    { category: 'higiene', name: 'Pasta de Dentes Branqueadora 90g',   price: 13.90, description: 'Clareamento e proteção contra cáries.',                          pexelsQuery: 'whitening toothpaste tube dental' },
    { category: 'higiene', name: 'Pasta de Dentes Sensodyne 50g',      price: 18.90, description: 'Para dentes sensíveis, proteção 24h.',                           pexelsQuery: 'sensitive teeth toothpaste dental' },
    { category: 'higiene', name: 'Escova de Dentes Macia',             price:  9.90, description: 'Cerdas macias com indicador de troca.',                          pexelsQuery: 'toothbrush soft bristle dental care' },
    { category: 'higiene', name: 'Fio Dental 50m',                     price:  8.90, description: 'Fio dental encerado sabor menta.',                               pexelsQuery: 'dental floss oral care hygiene' },
    { category: 'higiene', name: 'Desodorante Aerossol 150ml',         price: 16.90, description: 'Desodorante aerossol com proteção 48h.',                         pexelsQuery: 'deodorant aerosol spray personal care' },
    { category: 'higiene', name: 'Desodorante Roll-On 50ml',           price: 14.90, description: 'Roll-on com proteção 48h antitranspirante.',                     pexelsQuery: 'deodorant roll on personal care' },
    { category: 'higiene', name: 'Desodorante Stick 50g',              price: 15.90, description: 'Stick sólido sem álcool, proteção 72h.',                         pexelsQuery: 'deodorant stick solid antiperspirant' },
    { category: 'higiene', name: 'Sabonete Antibacteriano 90g',        price:  6.90, description: 'Elimina 99,9% das bactérias.',                                   pexelsQuery: 'antibacterial soap bar hygiene' },
    { category: 'higiene', name: 'Sabonete Líquido 250ml',             price: 12.90, description: 'Sabonete líquido hidratante para mãos.',                         pexelsQuery: 'liquid soap pump bottle hand wash' },
    { category: 'higiene', name: 'Álcool em Gel 70% 480ml',            price: 14.90, description: 'Higienizador de mãos 70% INPM, com hidratante.',                 pexelsQuery: 'hand sanitizer gel bottle 70' },
    { category: 'higiene', name: 'Absorvente Noturno 8 un',            price: 12.90, description: 'Com abas, proteção noturna máxima.',                             pexelsQuery: 'feminine pad overnight protection' },
    { category: 'higiene', name: 'Absorvente Diário 15 un',            price:  9.90, description: 'Protetor diário sem perfume.',                                   pexelsQuery: 'feminine daily pad liner' },
    { category: 'higiene', name: 'Absorvente Interno Regular 16 un',   price: 14.90, description: 'Tampon regular com aplicador.',                                  pexelsQuery: 'tampon feminine hygiene product' },
    { category: 'higiene', name: 'Papel Higiênico 12 rolos',           price: 22.90, description: 'Folha dupla macia, 12 rolos.',                                   pexelsQuery: 'toilet paper rolls hygiene' },
    { category: 'higiene', name: 'Lenços de Papel 100 folhas',         price:  8.90, description: 'Lenços faciais macios, 100 folhas.',                             pexelsQuery: 'facial tissues box soft' },
    { category: 'higiene', name: 'Cotonetes 100 un',                   price:  7.90, description: 'Hastes flexíveis com ponta de algodão.',                         pexelsQuery: 'cotton swabs buds hygiene' },
    { category: 'higiene', name: 'Lâmina de Barbear 2 un',             price: 12.90, description: 'Lâmina de barbear com 5 lâminas e faixa hidratante.',            pexelsQuery: 'shaving razor blade men grooming' },
    { category: 'higiene', name: 'Espuma de Barbear 200ml',            price: 14.90, description: 'Espuma com aloe vera para pele sensível.',                       pexelsQuery: 'shaving foam cream can men' },
    { category: 'higiene', name: 'Talco Polvilho 100g',                price: 10.90, description: 'Talco antisséptico para higiene diária.',                        pexelsQuery: 'talcum powder body hygiene' },
    { category: 'higiene', name: 'Esponja de Banho',                   price:  8.90, description: 'Esponja vegetal natural para banho.',                            pexelsQuery: 'bath sponge loofah natural' },
    { category: 'higiene', name: 'Creme para Barbear 75g',             price: 16.90, description: 'Creme de barbear hidratante para pele seca.',                    pexelsQuery: 'shaving cream tube men skincare' },
    { category: 'higiene', name: 'Kit Higiene Oral Viagem',            price: 24.90, description: 'Escova + pasta + fio dental + enxaguante.',                      pexelsQuery: 'travel dental kit oral hygiene set' },
    { category: 'higiene', name: 'Shampoo a Seco 150ml',               price: 26.90, description: 'Shampoo seco para higienização rápida.',                         pexelsQuery: 'dry shampoo spray hair care can' },
    // Bebê (30)
    { category: 'bebe', name: 'Fralda Pampers RN c/28',          price: 44.90, description: 'Recém-nascido até 4kg, 28 unidades.',                          pexelsQuery: 'newborn baby diapers small' },
    { category: 'bebe', name: 'Fralda Pampers P c/30',           price: 46.90, description: 'Tamanho P 4-8kg, 30 unidades.',                                pexelsQuery: 'baby diapers size small pampers' },
    { category: 'bebe', name: 'Fralda Pampers M c/30',           price: 49.90, description: 'Tamanho M 7-10kg, 30 unidades.',                               pexelsQuery: 'baby diapers pampers product' },
    { category: 'bebe', name: 'Fralda Pampers G c/28',           price: 52.90, description: 'Tamanho G 9-13kg, 28 unidades.',                               pexelsQuery: 'baby diapers large size soft' },
    { category: 'bebe', name: 'Fralda Huggies M c/32',           price: 48.90, description: 'Fralda Huggies Supreme M, 32 unidades.',                       pexelsQuery: 'huggies baby diaper soft' },
    { category: 'bebe', name: 'Lenços Umedecidos sem Álcool 80un',price: 14.90, description: 'Com aloe vera e camomila, sem álcool.',                        pexelsQuery: 'baby wipes clean gentle sensitive' },
    { category: 'bebe', name: 'Lenços Umedecidos 200 un',        price: 28.90, description: 'Embalagem econômica 200 lenços.',                              pexelsQuery: 'baby wipes large pack economy' },
    { category: 'bebe', name: 'Pomada Bepantol Baby 30g',        price: 28.90, description: 'Previne e trata assaduras com dexpantenol.',                   pexelsQuery: 'bepantol diaper rash cream baby care' },
    { category: 'bebe', name: 'Pomada Hipoglós 60g',             price: 22.90, description: 'Clássica pomada para prevenção de assaduras.',                 pexelsQuery: 'hipoglos diaper cream baby rash' },
    { category: 'bebe', name: 'Shampoo Johnson Baby 200ml',      price: 19.90, description: 'Shampoo suave sem lágrimas.',                                  pexelsQuery: 'baby shampoo gentle formula soft' },
    { category: 'bebe', name: 'Sabonete Líquido Baby 200ml',     price: 18.90, description: 'Sabonete corporal suave para bebês.',                          pexelsQuery: 'baby body wash liquid gentle' },
    { category: 'bebe', name: 'Loção Hidratante Baby 200ml',     price: 22.90, description: 'Loção corporal com óleo de amêndoas.',                         pexelsQuery: 'baby lotion moisturizer body' },
    { category: 'bebe', name: 'Talco Baby 200g',                 price: 18.90, description: 'Talco para bebê com camomila.',                                pexelsQuery: 'baby powder talc gentle skin' },
    { category: 'bebe', name: 'Soro Fisiológico Baby 10 amp',    price:  9.90, description: 'Ampolas 5ml para higiene nasal.',                              pexelsQuery: 'saline solution baby nasal drops' },
    { category: 'bebe', name: 'Soro Fisiológico 0,9% 500ml',     price: 12.90, description: 'Soro fisiológico frasco 500ml.',                               pexelsQuery: 'saline solution bottle medical' },
    { category: 'bebe', name: 'Termômetro Digital Axilar',       price: 36.90, description: 'Termômetro digital com alarme e memória.',                     pexelsQuery: 'digital thermometer baby temperature' },
    { category: 'bebe', name: 'Termômetro Infravermelho',        price: 89.90, description: 'Termômetro de testa sem contato.',                             pexelsQuery: 'infrared forehead thermometer contactless' },
    { category: 'bebe', name: 'Mamadeira Anti-Cólica 240ml',     price: 49.90, description: 'Sistema anti-cólica com bico fisiológico.',                    pexelsQuery: 'baby bottle anti colic feeding' },
    { category: 'bebe', name: 'Mamadeira 150ml',                 price: 38.90, description: 'Mamadeira para recém-nascido 150ml.',                          pexelsQuery: 'baby feeding bottle small newborn' },
    { category: 'bebe', name: 'Chupeta Ortodôntica 0-6m',        price: 22.90, description: 'Silicone ortodôntico para 0-6 meses.',                         pexelsQuery: 'baby pacifier orthodontic silicone' },
    { category: 'bebe', name: 'Chupeta Ortodôntica 6-18m',       price: 24.90, description: 'Silicone ortodôntico para 6-18 meses.',                        pexelsQuery: 'baby soother pacifier older' },
    { category: 'bebe', name: 'Monitor de Respiração Baby',      price: 149.90, description: 'Monitor de apneia com sensor de movimento.',                  pexelsQuery: 'baby breathing monitor sensor' },
    { category: 'bebe', name: 'Aspirador Nasal Baby',            price: 28.90, description: 'Aspirador nasal manual seguro para bebês.',                    pexelsQuery: 'baby nasal aspirator clear' },
    { category: 'bebe', name: 'Tesoura Baby',                    price: 18.90, description: 'Tesoura de ponta arredondada para unhas do bebê.',             pexelsQuery: 'baby scissors nail grooming kit' },
    { category: 'bebe', name: 'Cortador de Unhas Baby',          price: 22.90, description: 'Kit cortador e lixa de unhas para recém-nascido.',             pexelsQuery: 'baby nail clipper grooming set' },
    { category: 'bebe', name: 'Creme Dental Baby 50g',           price: 16.90, description: 'Gel dental sem flúor para bebês até 2 anos.',                  pexelsQuery: 'baby toothpaste fluoride free gentle' },
    { category: 'bebe', name: 'Escova Dental Baby',              price: 14.90, description: 'Escova com cerdas ultra-macias para bebês.',                   pexelsQuery: 'baby toothbrush soft small' },
    { category: 'bebe', name: 'Suporte para Mamadeira',          price: 34.90, description: 'Suporte aquecedor de mamadeira portátil.',                     pexelsQuery: 'bottle warmer baby feeding holder' },
    { category: 'bebe', name: 'Babador Impermeável 2un',         price: 28.90, description: 'Babador de silicone com bolso coletor.',                       pexelsQuery: 'silicone baby bib waterproof' },
    { category: 'bebe', name: 'Colônia Baby 200ml',              price: 38.90, description: 'Colônia suave com fragrância delicada para bebês.',            pexelsQuery: 'baby cologne perfume gentle soft' },
    // Beleza (22)
    { category: 'beleza', name: 'Hidratante Facial Neutrogena 100g',  price: 48.90, description: 'Oil-free com vitamina E para pele mista.',                  pexelsQuery: 'face moisturizer neutrogena skincare' },
    { category: 'beleza', name: 'Sérum Vitamina C 30ml',              price: 64.90, description: 'Sérum clareador e antioxidante com 20% Vit C.',            pexelsQuery: 'vitamin c face serum anti aging' },
    { category: 'beleza', name: 'Ácido Hialurônico Sérum 30ml',       price: 72.90, description: 'Hidratação profunda com ácido hialurônico.',               pexelsQuery: 'hyaluronic acid serum hydrating skincare' },
    { category: 'beleza', name: 'Tônico Facial Antioleosidade 200ml', price: 34.90, description: 'Controla oleosidade e minimiza poros.',                    pexelsQuery: 'facial toner bottle skincare' },
    { category: 'beleza', name: 'Esfoliante Facial 75g',              price: 28.90, description: 'Esfoliante com microesferas para pele lisa.',              pexelsQuery: 'face scrub exfoliator skincare' },
    { category: 'beleza', name: 'Máscara Facial de Argila 50g',       price: 24.90, description: 'Argila verde para limpeza profunda dos poros.',            pexelsQuery: 'clay face mask green beauty' },
    { category: 'beleza', name: 'Contorno Labial 3,5g',               price: 18.90, description: 'Lápis de lábio delineador duradouro.',                    pexelsQuery: 'lip liner pencil makeup beauty' },
    { category: 'beleza', name: 'Batom Matte Cremoso',                price: 29.90, description: 'Batom com acabamento matte de longa duração.',             pexelsQuery: 'matte lipstick red makeup beauty' },
    { category: 'beleza', name: 'Base Líquida Cobertura Total 30ml',  price: 54.90, description: 'Cobertura total com FPS 20, 24h de duração.',              pexelsQuery: 'liquid foundation makeup coverage' },
    { category: 'beleza', name: 'Corretivo Líquido 10ml',             price: 36.90, description: 'Corretivo de alta cobertura para olheiras.',               pexelsQuery: 'concealer liquid makeup coverage' },
    { category: 'beleza', name: 'Pó Compacto Universal',              price: 42.90, description: 'Pó finalizador translúcido para qualquer tom.',            pexelsQuery: 'compact powder makeup translucent' },
    { category: 'beleza', name: 'Máscara de Cílios Volume',           price: 38.90, description: 'Máscara para volume e alongamento dos cílios.',            pexelsQuery: 'mascara volume lashes makeup' },
    { category: 'beleza', name: 'Delineador Olhos Preto 1ml',         price: 22.90, description: 'Delineador líquido de ponta fina e precisa.',              pexelsQuery: 'eyeliner black liquid makeup precision' },
    { category: 'beleza', name: 'Sombra Paleta 12 Cores',             price: 48.90, description: 'Paleta com 12 tons neutros e coloridos.',                  pexelsQuery: 'eyeshadow palette colors makeup beauty' },
    { category: 'beleza', name: 'Demaquilante Bifásico 200ml',        price: 28.90, description: 'Remove maquiagem resistente à água.',                      pexelsQuery: 'makeup remover biphasic micellar water' },
    { category: 'beleza', name: 'Água Micelar 200ml',                 price: 26.90, description: 'Limpeza facial suave sem enxágue.',                        pexelsQuery: 'micellar water cleanser skincare bottle' },
    { category: 'beleza', name: 'Óleo de Rosa Mosqueta 30ml',         price: 44.90, description: 'Óleo cicatrizante para manchas e rugas.',                  pexelsQuery: 'rosehip oil face serum beauty' },
    { category: 'beleza', name: 'Esmalte Cremoso 7,5ml',              price:  9.90, description: 'Esmalte de secagem rápida cor intensa.',                   pexelsQuery: 'nail polish color lacquer beauty' },
    { category: 'beleza', name: 'Base e Top Coat Esmalte 7,5ml',      price: 11.90, description: 'Base fortalecedora e top coat brilhante.',                 pexelsQuery: 'nail base coat top coat polish' },
    { category: 'beleza', name: 'Removedor de Esmalte s/ Acetona 50ml',price: 12.90, description: 'Remove esmalte sem ressecar as unhas.',                   pexelsQuery: 'nail polish remover acetone free' },
    { category: 'beleza', name: 'Perfume Feminino 50ml',              price: 89.90, description: 'Eau de parfum floral com fixação de 12h.',                 pexelsQuery: 'feminine perfume bottle floral elegant' },
    { category: 'beleza', name: 'Perfume Masculino 100ml',            price: 94.90, description: 'Eau de toilette amadeirado e cítrico.',                    pexelsQuery: 'male cologne perfume bottle elegant' },
    // Genéricos (32)
    { category: 'genericos', name: 'Amoxicilina 500mg 21cp',       price: 22.90, description: 'Antibiótico amoxicilina 500mg, 21 cápsulas.',               pexelsQuery: 'antibiotic capsules medicine prescription', requiresPrescription: true  },
    { category: 'genericos', name: 'Amoxicilina + Clavulanato 875mg',price: 48.90, description: 'Antibiótico de amplo espectro.',                           pexelsQuery: 'amoxicillin antibiotic pills',               requiresPrescription: true  },
    { category: 'genericos', name: 'Azitromicina 500mg 3cp',        price: 28.90, description: 'Antibiótico azitromicina, dose única por 3 dias.',          pexelsQuery: 'azithromycin antibiotic tablets',            requiresPrescription: true  },
    { category: 'genericos', name: 'Ciprofloxacino 500mg 14cp',     price: 34.90, description: 'Antibiótico fluoroquinolona, 14 comprimidos.',              pexelsQuery: 'ciprofloxacin antibiotic medicine',          requiresPrescription: true  },
    { category: 'genericos', name: 'Metronidazol 400mg 14cp',       price: 18.90, description: 'Antibiótico e antiparasitário.',                            pexelsQuery: 'metronidazole antibiotic prescription',      requiresPrescription: true  },
    { category: 'genericos', name: 'Loratadina 10mg 12cp',          price: 12.90, description: 'Antialérgico não sedativo, 12 comprimidos.',                pexelsQuery: 'loratadine antiallergy tablets',             requiresPrescription: false },
    { category: 'genericos', name: 'Cetirizina 10mg 12cp',          price: 14.90, description: 'Antialérgico para rinite e urticária.',                     pexelsQuery: 'antihistamine allergy tablets medicine',     requiresPrescription: false },
    { category: 'genericos', name: 'Dexclorfeniramina 2mg xarope',  price: 16.90, description: 'Xarope antialérgico 120ml.',                               pexelsQuery: 'antiallergy syrup bottle medicine',          requiresPrescription: false },
    { category: 'genericos', name: 'Fluconazol 150mg 1cp',          price: 14.90, description: 'Antifúngico dose única para candidíase.',                   pexelsQuery: 'antifungal tablet medicine single dose',     requiresPrescription: false },
    { category: 'genericos', name: 'Nistatina Suspensão 50ml',      price: 22.90, description: 'Antifúngico oral suspensão para candidíase oral.',          pexelsQuery: 'nystatin antifungal suspension oral',        requiresPrescription: true  },
    { category: 'genericos', name: 'Mebendazol 100mg 6cp',          price: 12.90, description: 'Antiparasitário para lombriga e oxiúros.',                  pexelsQuery: 'antiparasitic medicine tablets worm',        requiresPrescription: false },
    { category: 'genericos', name: 'Ivermectina 6mg 2cp',           price: 16.90, description: 'Antiparasitário de amplo espectro.',                        pexelsQuery: 'ivermectin antiparasitic medicine',          requiresPrescription: true  },
    { category: 'genericos', name: 'Ranitidina 150mg 20cp',         price: 18.90, description: 'Antiácido para gastrite e úlcera péptica.',                 pexelsQuery: 'ranitidine gastric medicine tablets',        requiresPrescription: false },
    { category: 'genericos', name: 'Pantoprazol 40mg 14cp',         price: 26.90, description: 'Protetor gástrico para esofagite e gastrite.',              pexelsQuery: 'pantoprazole gastric protection capsule',    requiresPrescription: true  },
    { category: 'genericos', name: 'Domperidona 10mg 30cp',         price: 24.90, description: 'Antiemético para náuseas e vômitos.',                       pexelsQuery: 'antiemetic medicine nausea tablets',         requiresPrescription: false },
    { category: 'genericos', name: 'Metoclopramida 10mg 20cp',      price: 14.90, description: 'Antiemético e regulador do trânsito intestinal.',           pexelsQuery: 'metoclopramide antiemetic medicine',         requiresPrescription: true  },
    { category: 'genericos', name: 'Simeticona 125mg 10cp',         price:  9.90, description: 'Antiflatulento para gases e cólicas.',                      pexelsQuery: 'simethicone gas relief tablets stomach',     requiresPrescription: false },
    { category: 'genericos', name: 'Lactulose 667mg xarope 120ml',  price: 22.90, description: 'Laxante osmótico para constipação.',                        pexelsQuery: 'lactulose syrup laxative bottle',            requiresPrescription: false },
    { category: 'genericos', name: 'Bisacodil 5mg 20cp',            price: 12.90, description: 'Laxante estimulante para constipação.',                     pexelsQuery: 'laxative tablets constipation medicine',     requiresPrescription: false },
    { category: 'genericos', name: 'Losartana 50mg 30cp',           price: 28.90, description: 'Anti-hipertensivo bloqueador AT1.',                         pexelsQuery: 'losartan blood pressure medicine',           requiresPrescription: true  },
    { category: 'genericos', name: 'Enalapril 10mg 30cp',           price: 22.90, description: 'Inibidor da ECA para hipertensão.',                         pexelsQuery: 'enalapril hypertension medicine tablets',    requiresPrescription: true  },
    { category: 'genericos', name: 'Atenolol 50mg 30cp',            price: 18.90, description: 'Betabloqueador para hipertensão e arritmias.',              pexelsQuery: 'atenolol beta blocker heart medicine',       requiresPrescription: true  },
    { category: 'genericos', name: 'Anlodipino 5mg 30cp',           price: 24.90, description: 'Bloqueador de canal de cálcio para hipertensão.',           pexelsQuery: 'amlodipine calcium channel hypertension',    requiresPrescription: true  },
    { category: 'genericos', name: 'Sinvastatina 20mg 30cp',        price: 22.90, description: 'Redutor de colesterol.',                                    pexelsQuery: 'simvastatin cholesterol medicine',           requiresPrescription: true  },
    { category: 'genericos', name: 'Metformina 850mg 30cp',         price: 18.90, description: 'Antidiabético oral para diabetes tipo 2.',                  pexelsQuery: 'metformin diabetes medicine tablets',        requiresPrescription: true  },
    { category: 'genericos', name: 'Glibenclamida 5mg 30cp',        price: 14.90, description: 'Hipoglicemiante oral sulfonilureia.',                       pexelsQuery: 'glibenclamide diabetes oral medicine',       requiresPrescription: true  },
    { category: 'genericos', name: 'Levotiroxina 50mcg 30cp',       price: 24.90, description: 'Hormônio tireoidiano para hipotireoidismo.',                 pexelsQuery: 'levothyroxine thyroid medicine tablets',     requiresPrescription: true  },
    { category: 'genericos', name: 'Prednisolona 20mg 12cp',        price: 28.90, description: 'Corticosteroide para inflamações e alergias graves.',       pexelsQuery: 'prednisolone corticosteroid prescription',   requiresPrescription: true  },
    { category: 'genericos', name: 'Dexametasona 4mg 10cp',         price: 18.90, description: 'Corticosteroide de ação rápida.',                           pexelsQuery: 'dexamethasone corticosteroid medicine',      requiresPrescription: true  },
    { category: 'genericos', name: 'Escitalopram 10mg 30cp',        price: 54.90, description: 'Antidepressivo ISRS para depressão e ansiedade.',           pexelsQuery: 'escitalopram antidepressant prescription',   requiresPrescription: true  },
    { category: 'genericos', name: 'Amitriptilina 25mg 30cp',       price: 26.90, description: 'Antidepressivo tricíclico para dor crônica.',               pexelsQuery: 'amitriptyline antidepressant medicine',      requiresPrescription: true  },
    { category: 'genericos', name: 'Clonazepam 2mg 20cp',           price: 32.90, description: 'Ansiolítico benzodiazepínico — controle especial.',         pexelsQuery: 'clonazepam controlled medicine prescription', requiresPrescription: true  },
    { category: 'genericos', name: 'Dipirona IV 2ml amp',           price: 18.90, description: 'Dipirona injetável 500mg/ml, 5 ampolas.',                   pexelsQuery: 'injectable medicine ampoule pharmacy',       requiresPrescription: true  },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// Registry
// ─────────────────────────────────────────────────────────────────────────────

export const STORE_TEMPLATES = {
  pizzaria:                 PIZZARIA,
  hamburgueria:             HAMBURGUERIA,
  acai:                     ACAI,
  sorveteria:               SORVETERIA,
  farmacia:                 FARMACIA,
  drogaria:                 FARMACIA,
  farmacia_de_manipulacao:  FARMACIA,
};

/** Nichos permitidos para usuários PedeZap (delivery food) */
export const PEDEZAP_NICHES = ['pizzaria', 'hamburgueria', 'acai', 'sorveteria'];

/** Nichos permitidos para usuários FarmaZap */
export const FARMAZAP_NICHES = ['farmacia', 'drogaria', 'farmacia_de_manipulacao'];

/** Mapa type → niches para validação no storeFactory */
export const NICHES_BY_TYPE = {
  pedezap:  PEDEZAP_NICHES,
  farmazap: FARMAZAP_NICHES,
};

/**
 * Retorna o template para um nicho.
 * @param {string} niche
 * @returns {{ type, categories, products }}
 */
export function getTemplate(niche) {
  const key = niche.toLowerCase().trim();
  const template = STORE_TEMPLATES[key];
  if (!template) {
    throw Object.assign(
      new Error(`Nicho não suportado: "${niche}". Use: ${Object.keys(STORE_TEMPLATES).join(', ')}`),
      { statusCode: 400 }
    );
  }
  return template;
}

export const SUPPORTED_NICHES = Object.keys(STORE_TEMPLATES);
